"""
ScholAR - Pydantic data models for papers, authors, topics, and graph entities.
"""

from __future__ import annotations
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field


class Author(BaseModel):
    """Represents a paper author."""
    author_id: str = ""
    name: str
    affiliation: Optional[str] = None
    h_index: Optional[int] = None
    paper_count: Optional[int] = None


class Paper(BaseModel):
    """Represents an academic paper — the core entity."""
    paper_id: str
    title: str
    abstract: Optional[str] = ""
    authors: list[Author] = Field(default_factory=list)
    year: Optional[int] = None
    doi: Optional[str] = None
    url: Optional[str] = None
    venue: Optional[str] = None
    citation_count: int = 0
    reference_count: int = 0
    references: list[str] = Field(default_factory=list)
    citations: list[str] = Field(default_factory=list)
    source_api: str = ""
    embedding: Optional[list[float]] = None
    relevance_score: float = 0.0
    topics: list[str] = Field(default_factory=list)
    tldr: Optional[str] = None
    fields_of_study: list[str] = Field(default_factory=list)
    pdf_url: Optional[str] = None  # Direct PDF link if available

    def get_download_url(self) -> str:
        """Get best available URL for paper access."""
        if self.pdf_url:
            return self.pdf_url
        if self.doi:
            return f"https://doi.org/{self.doi}"
        if self.url:
            return self.url
        if "arxiv" in self.paper_id.lower():
            return f"https://arxiv.org/abs/{self.paper_id.replace('arxiv_', '')}"
        return ""

    def __hash__(self):
        return hash(self.paper_id)

    def __eq__(self, other):
        if isinstance(other, Paper):
            return self.paper_id == other.paper_id
        return False


class Topic(BaseModel):
    """Represents a research topic/theme extracted from clusters."""
    topic_id: str
    name: str
    description: Optional[str] = None
    paper_ids: list[str] = Field(default_factory=list)
    cluster_id: Optional[int] = None
    keyword_list: list[str] = Field(default_factory=list)


class ResearchGap(BaseModel):
    """A detected gap in the research landscape."""
    gap_id: str
    description: str
    confidence: float = 0.0
    related_topics: list[str] = Field(default_factory=list)
    suggested_directions: list[str] = Field(default_factory=list)


class Contradiction(BaseModel):
    """A detected contradiction between papers."""
    paper_a_id: str
    paper_b_id: str
    paper_a_claim: str
    paper_b_claim: str
    description: str
    confidence: float = 0.0


class Trend(BaseModel):
    """A detected temporal trend in research."""
    trend_id: str
    description: str
    topic: str
    start_year: Optional[int] = None
    end_year: Optional[int] = None
    direction: str = "rising"
    strength: float = 0.0
    paper_count_by_year: dict[int, int] = Field(default_factory=dict)


class SearchQuery(BaseModel):
    """A search query generated by the agent."""
    query_text: str
    strategy: str = ""
    source: str = "llm"


class AnalysisResult(BaseModel):
    """Aggregated analysis results from the graph."""
    clusters: list[Topic] = Field(default_factory=list)
    key_papers: list[str] = Field(default_factory=list)
    gaps: list[ResearchGap] = Field(default_factory=list)
    contradictions: list[Contradiction] = Field(default_factory=list)
    trends: list[Trend] = Field(default_factory=list)
    coverage_score: float = 0.0
    year_counts: dict[int, int] = Field(default_factory=dict)  # Raw year distribution


class ReportSection(BaseModel):
    """A section of the final literature review report."""
    title: str
    content: str
    order: int
    subsections: list[ReportSection] = Field(default_factory=list)
    figures: list[str] = Field(default_factory=list)


class TopPaperRecommendation(BaseModel):
    """A top paper recommended by ScholAR."""
    paper: Paper
    confidence: float = 0.0
    reason: str = ""


class LiteratureReport(BaseModel):
    """The final output: a complete literature review."""
    topic: str
    generated_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    total_papers_analyzed: int = 0
    sections: list[ReportSection] = Field(default_factory=list)
    references: list[Paper] = Field(default_factory=list)
    analysis: Optional[AnalysisResult] = None
    top_recommendations: list[TopPaperRecommendation] = Field(default_factory=list)
